/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:d7a02df4-9909-43af-a4e3-5f24f81dcb4c",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_hOD2Tv4MF",
    "aws_user_pools_web_client_id": "6nvun7jcuvvari0188muarkp9r",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://hqymlasjjjdc3itfmr2sxl5n4q.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ia5z7oxzdbcq5aczqws5d3z4ia",
    "aws_user_files_s3_bucket": "amplifyapp1804b76db21d42b0a783c667f64b651d222215-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
